default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: memory_well_development

test:
  <<: *default
  database: memory_well_test

production:
  <<: *default
  database: memory_well_production
